[package]

name = "cssparser"
version = "0.8.0"
authors = [ "Simon Sapin <simon.sapin@exyr.org>" ]

description = "Rust implementation of CSS Syntax Level 3"
documentation = "http://servo.github.io/rust-cssparser/cssparser/index.html"
repository = "https://github.com/servo/rust-cssparser"
readme = "README.md"
keywords = ["css", "syntax", "parser"]
license = "MPL-2.0"
build = "build.rs"

exclude = ["src/css-parsing-tests"]

[dev-dependencies]
rustc-serialize = "0.3"
tempdir = "0.3"

[dependencies]
encoding = "0.2"
heapsize = {version = "0.3", optional = true}
matches = "0.1"
serde = {version = "0.9", optional = true}

[build-dependencies]
syn = { version = "0.10.6", features = ["full", "visit"]}
quote = "0.3"

[features]
bench = []
dummy_match_byte = []
