[package]

name = "cssparser"
version = "0.5.4"
authors = [ "Simon Sapin <simon.sapin@exyr.org>" ]

description = "Rust implementation of CSS Syntax Level 3"
documentation = "http://servo.github.io/rust-cssparser/cssparser/index.html"
repository = "https://github.com/servo/rust-cssparser"
readme = "README.md"
keywords = ["css", "syntax", "parser"]
license = "MPL-2.0"


[dev-dependencies]
rustc-serialize = "0.3"
tempdir = "0.3"

[dependencies]
encoding = "0.2"
heapsize = {version = ">=0.1.1, <0.4.0", optional = true}
heapsize_plugin = {version = "0.1.0", optional = true}
matches = "0.1"
serde = {version = ">=0.6.6, <0.8", optional = true}
serde_macros = {version = ">=0.6.5, <0.8", optional = true}

[features]
serde-serialization = [ "serde", "serde_macros" ]
heap_size = [ "heapsize", "heapsize_plugin" ]
